name: dotnet package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        dotnet-version: [ '8.1.x', '10.0.x' ] # [10.0.107] #[ '8.1.x', '10.0.x' ]

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v6
      
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Show installed SDKs
        run: dotnet --list-sdks
        
      - name: Verify dotnet version
        run: |
          dotnet --version
          dotnet --info

      # Prints the image used to run the tests
      - name: Show runner image
        run: |
          echo "ImageOS=$ImageOS"
          echo "ImageVersion=$ImageVersion"

      - name: Show OS information (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          echo "Runner OS: $RUNNER_OS"

          if [ "$RUNNER_OS" = "Linux" ]; then
            cat /etc/os-release
          elif [ "$RUNNER_OS" = "macOS" ]; then
            sw_vers
          fi

      - name: Show OS information (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Write-Host "Runner OS: $env:RUNNER_OS"
          systeminfo | Select-String "OS Name","OS Version"
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: Test with the dotnet CLI
        run: dotnet test --no-build
